### ISSUE TITLE
Type checking: if multiple arguments have the same type, it is unclear which argument causes a type violation

### ISSUE THREAD

**Issue by skogsbaer** [skogsbaer/write-your-python-program#5] opened 2021-09-22 11:39 UTC
Execute

```
PYTHONPATH=site-lib/ python3 src/runYourProgram.py test-data/testTypesCollections3.py
```

from inside the python subdirectory in order to reproduce. 

The output is:

```
untypy.error.UntypyTypeError
given:    'foo'
expected: value of type int

context: list[int]
              ^^^
declared at: test-data/testTypesCollections3.py:3
  3 | def appendSomething(l: list[int], l2: list[int]) -> None:
  4 |     l.append("foo")

caused by: test-data/testTypesCollections3.py:4
  4 |     l.append("foo")
```

Does the `l` or the`l2` parameter cause the violation?

**Comment by skogsbaer** [comment] 2021-09-22 12:14
Here is a better error message:

```
untypy.error.UntypyTypeError
given:    'foo'
expected: value of type int

declared at: test-data/testTypesCollections3.py:3
  3 | def appendSomething(l: list[int], l2: list[int]) -> None:
                                                         ^^^

caused by: test-data/testTypesCollections3.py:4
  4 |     l.append("foo")
```

There is some redudancy between the "context" and the "declared at" part. (In other situations, the "context" part even includes the whole function signature.) So why not drop the context part and include the very helpful location indicator `^^^` in the "declared at" part?

**Comment by CodeSteak** [comment] 2021-09-23 14:59
Currently the context displays only the type signature if it was violated, so it is clear which parameter (displayed in the caused by part) has caused the type error.
In the case of the example above the caller of `list.append` is solely responsible for the violation, so only the expected type of the list is shown.

Highlighting the exact position of the declaration inside the source would be helpful, but it is also very hard. 
Maybe it can be done using the inspect-module when at time of resolving the `TypeChecker`. 
I am not sure how feasible this is, but i will look into it.

**Comment by skogsbaer** [comment] 2021-09-23 17:29
Ok, if this is costly this implement, we should defer this issue. It's not a real bug, only an improvement.

**Closed** 2022-03-10 11:57 UTC
Labels: tycheck, important, improvement, size L
